services:
  slack-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Slack OAuth credentials (set these in .env file)
      - SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
      - SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET}
      # Optional: For testing cloud behavior locally
      - MCP_ENV=local
      # Token storage path
      - TOKEN_STORAGE_PATH=/app/data/slack_tokens.jsonl
      # Docker environment flag
      - DOCKER_ENV=true
    volumes:
      # Persist token storage between restarts
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - slack-mcp-network

networks:
  slack-mcp-network:
    driver: bridge